// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcu6IjjToq_Q70zz8QuxXxG5Y98HcxPc0',
    appId: '1:638876158882:web:78f70b8b1db6e68d14c0fb',
    messagingSenderId: '638876158882',
    projectId: 'busnow-applications',
    authDomain: 'busnow-applications.firebaseapp.com',
    storageBucket: 'busnow-applications.firebasestorage.app',
    databaseURL: 'https://busnow-applications-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0SEksxHyb5UDm7cMmVNpOYi5zlbFLObg',
    appId: '1:638876158882:android:fdef8ef19fdfe5fd14c0fb',
    messagingSenderId: '638876158882',
    projectId: 'busnow-applications',
    storageBucket: 'busnow-applications.firebasestorage.app',
    databaseURL: 'https://busnow-applications-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLyr8nJG6-IGdFv7deGhp9Zc_HwjKIx_w',
    appId: '1:638876158882:ios:558d1dc2619f5c0c14c0fb',
    messagingSenderId: '638876158882',
    projectId: 'busnow-applications',
    storageBucket: 'busnow-applications.firebasestorage.app',
    iosBundleId: 'com.example.schoolNow',
    databaseURL: 'https://busnow-applications-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLyr8nJG6-IGdFv7deGhp9Zc_HwjKIx_w',
    appId: '1:638876158882:ios:558d1dc2619f5c0c14c0fb',
    messagingSenderId: '638876158882',
    projectId: 'busnow-applications',
    storageBucket: 'busnow-applications.firebasestorage.app',
    iosBundleId: 'com.example.schoolNow',
    databaseURL: 'https://busnow-applications-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcu6IjjToq_Q70zz8QuxXxG5Y98HcxPc0',
    appId: '1:638876158882:web:0b475368d06a8fda14c0fb',
    messagingSenderId: '638876158882',
    projectId: 'busnow-applications',
    authDomain: 'busnow-applications.firebaseapp.com',
    storageBucket: 'busnow-applications.firebasestorage.app',
    databaseURL: 'https://busnow-applications-default-rtdb.firebaseio.com',
  );
}
